theme: jekyll-theme-minimal
title: "Jeffrey L. Gould"
description: "Distinguished Professor and James H. Rudy Professor, Department of History"
logo: /assets/img/gould_jeff.jpg
author: "Jeffrey L. Gould"
