theme: jekyll-theme-minimal
title: "Tuberculous Imaginaries"
description: "A Media Art Installation on the History of Tuberculosis by Sean Purcell"
logo: /images/TI_ProdStill1.jpg
author: "Jeffrey L. Gould"
