theme: jekyll-theme-minimal
title: "Tuberculous Imaginaries"
description: "A Media Art Installation on the History of Tuberculosis by Sean Purcell"
logo: /images/Ifell1_Projectorb_2.png
author: "Sean Purcell"
